CANVAS_WIDTH = 650
CANVAS_HEIGHT = 450
PADDLE_LENGTH = 15
PADDLE_THICKNESS = 75
PADDING = PADDLE_LENGTH * 2
BALL_SIZE = 15
REFLECTION_ANGLE = 45
# マルチ対戦用
CANVAS_WIDTH_MULTI = 650
CANVAS_HEIGHT_MULTI = 650
PADDING_MULTI = PADDLE_LENGTH * 2
